name: cvlsu-ucvm-ci

on:
  push:
##    branches: [ main ]
    branches: [ foofoo ]

jobs:
  cvlsu-build-ucvm-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/cvlsu/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvlsu/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - name: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: main
        path: ucvm
    - id: build-ucvm
      name: build ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'cvlsu'
         target-model: 'cvlsu'
    - name: get-result
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock cvlsu away
      run: (rm -rf $RUNNER_WORKSPACE/cvlsu/ucvm/work/model/cvlsu)
      shell: bash
### build cvlsu from github 
    - name: checkout cvlsu main
      uses: actions/checkout@v2
      with: 
        path: cvlsu
    - name: move it to the right location
      run: (mv cvlsu $RUNNER_WORKSPACE/cvlsu/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build cvlsu as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/cvlsu/ucvm/work/model/cvlsu; ./.github/scripts/cvlsu-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test cvlsu with ucvm
      run: (cd $RUNNER_WORKSPACE/cvlsu/ucvm/work/model/cvlsu; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/cvlsu-test-ucvm.sh)
      shell: bash
    - name: test cvlsu under ucvm
      run: (cd $RUNNER_WORKSPACE/cvlsu/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash

  cvlsu-build-ucvm-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/cvlsu/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvlsu/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - name: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: main
        path: ucvm
    - id: build-ucvm
      name: build ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'cvlsu'
         target-model: 'cvlsu'
    - name: get-result
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock cvlsu away
      run: (rm -rf $RUNNER_WORKSPACE/cvlsu/ucvm/work/model/cvlsu)
      shell: bash
### build cvlsu from github 
    - name: checkout cvlsu main
      uses: actions/checkout@v2
      with: 
        path: cvlsu
    - name: move it to the right location
      run: (mv cvlsu $RUNNER_WORKSPACE/cvlsu/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build cvlsu as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/cvlsu/ucvm/work/model/cvlsu; ./.github/scripts/cvlsu-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test cvlsu with ucvm
      run: (cd $RUNNER_WORKSPACE/cvlsu/ucvm/work/model/cvlsu; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/cvlsu-test-ucvm.sh)
      shell: bash
    - name: test cvlsu under ucvm
      run: (cd $RUNNER_WORKSPACE/cvlsu/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash





